"""added Foreign Key to reviews

Revision ID: 47819f691286
Revises: d92e3896b97f
Create Date: 2024-01-10 10:10:32.545604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47819f691286'
down_revision = 'd92e3896b97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
